[2025-06-30T09:18:28.509+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T09:18:28.529+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_checkout_pipeline.auto_run_dbt scheduled__2025-06-30T08:30:00+00:00 [queued]>
[2025-06-30T09:18:28.532+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_checkout_pipeline.auto_run_dbt scheduled__2025-06-30T08:30:00+00:00 [queued]>
[2025-06-30T09:18:28.532+0000] {taskinstance.py:2303} INFO - Starting attempt 4 of 6
[2025-06-30T09:18:28.538+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): auto_run_dbt> on 2025-06-30 08:30:00+00:00
[2025-06-30T09:18:28.540+0000] {standard_task_runner.py:63} INFO - Started process 573 to run task
[2025-06-30T09:18:28.543+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_checkout_pipeline', 'auto_run_dbt', 'scheduled__2025-06-30T08:30:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/automatic_run_dbt.py', '--cfg-path', '/tmp/tmpg1lczka4']
[2025-06-30T09:18:28.544+0000] {standard_task_runner.py:91} INFO - Job 30: Subtask auto_run_dbt
[2025-06-30T09:18:28.555+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-30T09:18:28.579+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_checkout_pipeline.auto_run_dbt scheduled__2025-06-30T08:30:00+00:00 [running]> on host 010e8135382b
[2025-06-30T09:18:28.712+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hosi04' AIRFLOW_CTX_DAG_ID='dbt_run_checkout_pipeline' AIRFLOW_CTX_TASK_ID='auto_run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T08:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-06-30T08:30:00+00:00'
[2025-06-30T09:18:28.713+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T09:18:28.719+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-30T09:18:28.720+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/.dbt/']
[2025-06-30T09:18:28.726+0000] {subprocess.py:86} INFO - Output:
[2025-06-30T09:18:29.995+0000] {subprocess.py:93} INFO - [0m09:18:29  Running with dbt=1.10.2
[2025-06-30T09:18:30.135+0000] {subprocess.py:93} INFO - [0m09:18:30  Registered adapter: clickhouse=1.9.2
[2025-06-30T09:18:30.395+0000] {subprocess.py:93} INFO - [0m09:18:30  Found 4 models, 2 sources, 476 macros
[2025-06-30T09:18:30.396+0000] {subprocess.py:93} INFO - [0m09:18:30
[2025-06-30T09:18:30.396+0000] {subprocess.py:93} INFO - [0m09:18:30  Concurrency: 1 threads (target='dev')
[2025-06-30T09:18:30.396+0000] {subprocess.py:93} INFO - [0m09:18:30
[2025-06-30T09:18:30.868+0000] {subprocess.py:93} INFO - [0m09:18:30  1 of 4 START sql table model `tracking_problem_stg`.`stg_add_to_cart` .......... [RUN]
[2025-06-30T09:18:30.942+0000] {subprocess.py:93} INFO - [0m09:18:30  1 of 4 OK created sql table model `tracking_problem_stg`.`stg_add_to_cart` ..... [[32mOK[0m in 0.07s]
[2025-06-30T09:18:30.943+0000] {subprocess.py:93} INFO - [0m09:18:30  2 of 4 START sql table model `tracking_problem_stg`.`stg_checkout_items` ....... [RUN]
[2025-06-30T09:18:30.960+0000] {subprocess.py:93} INFO - [0m09:18:30  2 of 4 OK created sql table model `tracking_problem_stg`.`stg_checkout_items` .. [[32mOK[0m in 0.02s]
[2025-06-30T09:18:30.962+0000] {subprocess.py:93} INFO - [0m09:18:30  3 of 4 START sql table model `tracking_problem_int`.`int_checkout_items` ....... [RUN]
[2025-06-30T09:18:30.990+0000] {subprocess.py:93} INFO - [0m09:18:30  3 of 4 OK created sql table model `tracking_problem_int`.`int_checkout_items` .. [[32mOK[0m in 0.03s]
[2025-06-30T09:18:30.992+0000] {subprocess.py:93} INFO - [0m09:18:30  4 of 4 START sql table model `tracking_problem_mart`.`mart_checkout_items` ..... [RUN]
[2025-06-30T09:18:31.016+0000] {subprocess.py:93} INFO - [0m09:18:31  4 of 4 OK created sql table model `tracking_problem_mart`.`mart_checkout_items`  [[32mOK[0m in 0.02s]
[2025-06-30T09:18:31.019+0000] {subprocess.py:93} INFO - [0m09:18:31
[2025-06-30T09:18:31.019+0000] {subprocess.py:93} INFO - [0m09:18:31  Finished running 4 table models in 0 hours 0 minutes and 0.62 seconds (0.62s).
[2025-06-30T09:18:31.037+0000] {subprocess.py:93} INFO - [0m09:18:31
[2025-06-30T09:18:31.037+0000] {subprocess.py:93} INFO - [0m09:18:31  [32mCompleted successfully[0m
[2025-06-30T09:18:31.038+0000] {subprocess.py:93} INFO - [0m09:18:31
[2025-06-30T09:18:31.038+0000] {subprocess.py:93} INFO - [0m09:18:31  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-30T09:18:32.591+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-30T09:18:32.591+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/dbt", line 8, in <module>
[2025-06-30T09:18:32.592+0000] {subprocess.py:93} INFO -     sys.exit(cli())
[2025-06-30T09:18:32.593+0000] {subprocess.py:93} INFO -              ^^^^^
[2025-06-30T09:18:32.593+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2025-06-30T09:18:32.593+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-06-30T09:18:32.593+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.593+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2025-06-30T09:18:32.593+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2025-06-30T09:18:32.594+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt/cli/main.py", line 149, in wrapper
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt/cli/requires.py", line 190, in wrapper
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -     fire_event(
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/functions.py", line 142, in fire_event
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -     get_event_manager().fire_event(
[2025-06-30T09:18:32.595+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/event_manager.py", line 56, in fire_event
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -     msg = msg_from_base_event(e, level=level)
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/base_types.py", line 140, in msg_from_base_event
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -     "msg": event.message(),
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt/events/types.py", line 2400, in message
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -     return f"Resource report: {self.to_json()}"
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -                                ^^^^^^^^^^^^^^
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/base_types.py", line 98, in to_json
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -     return MessageToJson(
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^
[2025-06-30T09:18:32.596+0000] {subprocess.py:93} INFO - TypeError: MessageToJson() got an unexpected keyword argument 'always_print_fields_with_no_presence'
[2025-06-30T09:18:32.934+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-30T09:18:32.934+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T09:18:32.941+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-30T09:18:32.943+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_checkout_pipeline, task_id=auto_run_dbt, execution_date=20250630T083000, start_date=20250630T091828, end_date=20250630T091832
[2025-06-30T09:18:32.957+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 30 for task auto_run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 573)
[2025-06-30T09:18:32.997+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T09:18:33.008+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T09:18:33.008+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
