[2025-06-30T10:31:25.686+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-30T10:31:25.706+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_checkout_pipeline.auto_run_dbt manual__2025-06-30T09:10:13.494775+00:00 [queued]>
[2025-06-30T10:31:25.801+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_checkout_pipeline.auto_run_dbt manual__2025-06-30T09:10:13.494775+00:00 [queued]>
[2025-06-30T10:31:25.801+0000] {taskinstance.py:2303} INFO - Starting attempt 10 of 12
[2025-06-30T10:31:25.816+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): auto_run_dbt> on 2025-06-30 09:10:13.494775+00:00
[2025-06-30T10:31:25.820+0000] {standard_task_runner.py:63} INFO - Started process 493 to run task
[2025-06-30T10:31:25.822+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_checkout_pipeline', 'auto_run_dbt', 'manual__2025-06-30T09:10:13.494775+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/automatic_run_dbt.py', '--cfg-path', '/tmp/tmpiotarhkz']
[2025-06-30T10:31:25.824+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask auto_run_dbt
[2025-06-30T10:31:25.835+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-06-30T10:31:25.854+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_run_checkout_pipeline.auto_run_dbt manual__2025-06-30T09:10:13.494775+00:00 [running]> on host 67c12b90f73b
[2025-06-30T10:31:25.902+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hosi04' AIRFLOW_CTX_DAG_ID='dbt_run_checkout_pipeline' AIRFLOW_CTX_TASK_ID='auto_run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2025-06-30T09:10:13.494775+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-30T09:10:13.494775+00:00'
[2025-06-30T10:31:25.903+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-30T10:31:25.910+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-06-30T10:31:25.910+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt && dbt run --profiles-dir /opt/***/.dbt/']
[2025-06-30T10:31:25.918+0000] {subprocess.py:86} INFO - Output:
[2025-06-30T10:31:27.212+0000] {subprocess.py:93} INFO - [0m10:31:27  Running with dbt=1.10.2
[2025-06-30T10:31:27.358+0000] {subprocess.py:93} INFO - [0m10:31:27  Registered adapter: clickhouse=1.9.2
[2025-06-30T10:31:27.616+0000] {subprocess.py:93} INFO - [0m10:31:27  Found 4 models, 2 sources, 476 macros
[2025-06-30T10:31:27.618+0000] {subprocess.py:93} INFO - [0m10:31:27
[2025-06-30T10:31:27.618+0000] {subprocess.py:93} INFO - [0m10:31:27  Concurrency: 1 threads (target='dev')
[2025-06-30T10:31:27.618+0000] {subprocess.py:93} INFO - [0m10:31:27
[2025-06-30T10:31:28.075+0000] {subprocess.py:93} INFO - [0m10:31:28  1 of 4 START sql table model `tracking_problem_stg`.`stg_add_to_cart` .......... [RUN]
[2025-06-30T10:31:28.140+0000] {subprocess.py:93} INFO - [0m10:31:28  1 of 4 OK created sql table model `tracking_problem_stg`.`stg_add_to_cart` ..... [[32mOK[0m in 0.06s]
[2025-06-30T10:31:28.141+0000] {subprocess.py:93} INFO - [0m10:31:28  2 of 4 START sql table model `tracking_problem_stg`.`stg_checkout_items` ....... [RUN]
[2025-06-30T10:31:28.157+0000] {subprocess.py:93} INFO - [0m10:31:28  2 of 4 OK created sql table model `tracking_problem_stg`.`stg_checkout_items` .. [[32mOK[0m in 0.02s]
[2025-06-30T10:31:28.159+0000] {subprocess.py:93} INFO - [0m10:31:28  3 of 4 START sql table model `tracking_problem_int`.`int_checkout_items` ....... [RUN]
[2025-06-30T10:31:28.174+0000] {subprocess.py:93} INFO - [0m10:31:28  3 of 4 OK created sql table model `tracking_problem_int`.`int_checkout_items` .. [[32mOK[0m in 0.01s]
[2025-06-30T10:31:28.176+0000] {subprocess.py:93} INFO - [0m10:31:28  4 of 4 START sql table model `tracking_problem_mart`.`mart_checkout_items` ..... [RUN]
[2025-06-30T10:31:28.194+0000] {subprocess.py:93} INFO - [0m10:31:28  4 of 4 OK created sql table model `tracking_problem_mart`.`mart_checkout_items`  [[32mOK[0m in 0.02s]
[2025-06-30T10:31:28.197+0000] {subprocess.py:93} INFO - [0m10:31:28
[2025-06-30T10:31:28.198+0000] {subprocess.py:93} INFO - [0m10:31:28  Finished running 4 table models in 0 hours 0 minutes and 0.58 seconds (0.58s).
[2025-06-30T10:31:28.220+0000] {subprocess.py:93} INFO - [0m10:31:28
[2025-06-30T10:31:28.220+0000] {subprocess.py:93} INFO - [0m10:31:28  [32mCompleted successfully[0m
[2025-06-30T10:31:28.220+0000] {subprocess.py:93} INFO - [0m10:31:28
[2025-06-30T10:31:28.220+0000] {subprocess.py:93} INFO - [0m10:31:28  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 NO-OP=0 TOTAL=4
[2025-06-30T10:31:29.827+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-06-30T10:31:29.827+0000] {subprocess.py:93} INFO -   File "/home/***/.local/bin/dbt", line 8, in <module>
[2025-06-30T10:31:29.827+0000] {subprocess.py:93} INFO -     sys.exit(cli())
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -              ^^^^^
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1078, in main
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.828+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2025-06-30T10:31:29.829+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -     return f(get_current_context(), *args, **kwargs)
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt/cli/main.py", line 149, in wrapper
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt/cli/requires.py", line 190, in wrapper
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -     fire_event(
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/functions.py", line 142, in fire_event
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -     get_event_manager().fire_event(
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/event_manager.py", line 56, in fire_event
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -     msg = msg_from_base_event(e, level=level)
[2025-06-30T10:31:29.830+0000] {subprocess.py:93} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/base_types.py", line 140, in msg_from_base_event
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -     "msg": event.message(),
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt/events/types.py", line 2400, in message
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -     return f"Resource report: {self.to_json()}"
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -                                ^^^^^^^^^^^^^^
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.11/site-packages/dbt_common/events/base_types.py", line 98, in to_json
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -     return MessageToJson(
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^
[2025-06-30T10:31:29.831+0000] {subprocess.py:93} INFO - TypeError: MessageToJson() got an unexpected keyword argument 'always_print_fields_with_no_presence'
[2025-06-30T10:31:30.182+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-06-30T10:31:30.183+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-30T10:31:30.191+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-06-30T10:31:30.194+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_run_checkout_pipeline, task_id=auto_run_dbt, execution_date=20250630T091013, start_date=20250630T103125, end_date=20250630T103130
[2025-06-30T10:31:30.199+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task auto_run_dbt (Bash command failed. The command returned a non-zero exit code 1.; 493)
[2025-06-30T10:31:30.233+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-30T10:31:30.246+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-30T10:31:30.247+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
